# Generated by Django 5.1.2 on 2024-11-04 02:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0002_gender_medicalhistory_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=11)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='petcare.address')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petcare.clinic')),
            ],
        ),
    ]
