# Generated by Django 5.1.2 on 2024-11-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0006_pet_weight_alter_clinic_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
