# Generated by Django 5.1.3 on 2024-11-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0009_alter_owner_cpf_alter_owner_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
