# Generated by Django 5.1.3 on 2024-11-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0010_remove_owner_occupation_alter_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
