# Generated by Django 5.1.3 on 2024-11-26 14:01

import petcare.models.owner
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0012_vet_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(null=True, upload_to=petcare.models.owner.upload_image),
        ),
    ]
