# Generated by Django 5.1.3 on 2024-11-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0013_alter_owner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
