# Generated by Django 5.1.3 on 2024-11-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0014_alter_illness_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
