# Generated by Django 5.1.3 on 2024-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0015_alter_surgery_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
